task: oos_videoqa
tag: custom_videoqa

dataset_path: json
dataset_kwargs:
  data_files:
    # test: evaluation/data/vqa/selected_250_sorted_ranges_step23_decoy_other_video_neutralprompt.jsonl
    # test: /work/courses/3dv/team1/data/vqa/selected_250_sorted_ranges.jsonl
    test: /cluster/home/fangma/scratch/data/vqa/multi_turn_P01_P04.jsonl
    # test: /cluster/home/fangma/scratch/data/vqa/sanity.jsonl



test_split: test

output_type: generate_until

process_docs: !function utils.process_docs
doc_to_visual: !function utils.oos_doc_to_visual
doc_to_text: !function utils.oos_doc_to_text
doc_to_messages: !function utils.oos_doc_to_messages_with_visuals
doc_to_target: "answer"
process_results: !function utils.oos_process_results

generation_kwargs:
  max_new_tokens: 640
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

metric_list:
  - metric: oos_score
    aggregation: !function utils.oos_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    system_prompt: "You are a helpful assistant trained to answer spatial and visual questions based on egocentric videos. The videos are captured from a first-person perspective and may contain various objects and interactions. Use the video to answer the question. The video is sampled at 1 frame per second."
    #system_prompt: ""
metadata:
  version: 0.4
  mode: multi_turn_chat_mixed

cluster_key: source_video_id
